
logging:
  level:
    root: INFO
    org.springframework.security: INFO

server:
  context-path: /employeeconnect
  port: 8082

# Defaulting the profile to use the prosper settings
spring:
  profiles:
    active: prosper, prosper-qa32
