
logging:
  level:
    root: INFO
    org.springframework.security: INFO

server:
  context-path: /employeeconnect
  port: 8082

# Use the appropriate settings below
employee-connect:
  ldap:
    urls:
    root-dn:
    domain:

# Defaulting the profile to use the prosper settings
spring:
  profiles:
    active: prosper

#spring.mvc.view.prefix: /static/ # Spring MVC view prefix.
#spring.mvc.view.suffix: .html # Spring MVC view suffix.
#spring.mvc.static-path-pattern: /resources/static/**
