
logging:
  level:
    root: INFO
    org.springframework.security: INFO

server:
  context-path: /employeeconnect
  port: 8082

# Use the appropriate settings below
employee-connect:
  ldap:
    urls:
    root-dn:
    domain:

# Defaulting the profile to use the prosper settings
spring:
  profiles:
    active: prosper
